apiVersion: v1
kind: Pod
metadata:
  name: dask-scheduler
  labels:
    cluster_type: dask
    dask_type: scheduler
spec:
  restartPolicy: Never
  containers:
  # TODO: update image to official image
    - image: isvoid/rapidsai-cloud-worker:22.06-cuda11.5-runtime-ubuntu20.04-py3.9
      imagePullPolicy: IfNotPresent 
      env:
      - name: DISABLE_JUPYTER
        value: "true"
      args: [ dask-scheduler ]
      name: dask-scheduler
      resources:
        limits:
          cpu: "2"
          memory: 3G
        requests:
          cpu: "2"
          memory: 3G
