kind: Pod
metadata:
  labels:
    dask_type: scheduler
spec:
  restartPolicy: Never
  containers:
    - image: rapidsai/rapidsai-core-nightly:22.06-cuda11.5-runtime-ubuntu20.04-py3.9
      imagePullPolicy: IfNotPresent 
      env:
      - name: DISABLE_JUPYTER
        value: "true"
      args: [ dask-scheduler ]
      name: dask-scheduler
      resources:
        limits:
          cpu: "3"
          memory: 12G
          nvidia.com/gpu: 1
        requests:
          cpu: "3"
          memory: 12G
