apiVersion: v1
kind: Pod
metadata:
  labels:
    cluster_type: dask
    dask_type: GPU_worker
spec:
  restartPolicy: Never
  containers:
    - image: rapidsai/rapidsai-core:22.06-cuda11.5-runtime-ubuntu20.04-py3.9
      imagePullPolicy: IfNotPresent
      env:
      - name: DISABLE_JUPYTER
        value: "true"
      - name: EXTRA_PIP_PACKAGES
        value: "gcsfs"
      args: [ dask-cuda-worker, $(DASK_SCHEDULER_ADDRESS), --rmm-managed-memory ]
      name: dask-cuda-worker
      resources:
        limits:
          cpu: "2"
          memory: 3G
          nvidia.com/gpu: 1
        requests:
          cpu: "2"
          memory: 3G
          nvidia.com/gpu: 1
