kind: Pod
metadata:
  labels:
    dask_type: GPU_worker
spec:
  restartPolicy: Never
  containers:
    - image: rapidsai/rapidsai-core-nightly:22.08-cuda11.5-runtime-ubuntu20.04-py3.9
      imagePullPolicy: IfNotPresent
      env:
        - name: DISABLE_JUPYTER
          value: true
      args: [ dask-cuda-worker, $(DASK_SCHEDULER_ADDRESS), --rmm-managed-memory ]
      name: dask-cuda-worker
      resources:
        limits:
          cpu: "3"
          memory: 12G
          nvidia.com/gpu: 1
        requests:
          cpu: "3"
          memory: 12G
          nvidia.com/gpu: 1
