apiVersion: v1
kind: Pod
metadata:
  labels:
    cluster_type: dask
    dask_type: GPU_worker
spec:
  restartPolicy: Never
  containers:
  # TODO: update image to official image
    - image: isvoid/rapidsai-cloud-worker:22.06-cuda11.5-runtime-ubuntu20.04-py3.9
      imagePullPolicy: Always
      env:
      - name: DISABLE_JUPYTER
        value: "true"
      args: [ dask-cuda-worker, $(DASK_SCHEDULER_ADDRESS), --rmm-managed-memory ]
      name: dask-cuda-worker
      # Optimized against GCP n1-standard-4 P100 nodes to increase occupancy.
      # Other node pool setup may require different setups
      resources:
        limits:
          cpu: "2"
          memory: 3G
          nvidia.com/gpu: 1
        requests:
          cpu: "2"
          memory: 3G
          nvidia.com/gpu: 1
